# Generated by Django 5.1.5 on 2025-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necrosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, help_text='User contact information (phone, etc.)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, help_text='User organisation or affiliation', max_length=128, null=True),
        ),
    ]
