# Generated by Django 5.1.5 on 2025-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necrosis', '0002_user_contact_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='session_name',
            field=models.CharField(blank=True, help_text='User-editable session name', max_length=128, null=True),
        ),
    ]
