name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BACKEND_IMAGE: backend
  FRONTEND_IMAGE: frontend
  LATEST_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Debug directory structure
      run: |
        pwd
        ls -la
        echo "Checking NecrosisApi directory:"
        ls -la NecrosisApi/
        echo "Checking necrosisapp directory:"
        ls -la necrosisapp/

    - name: Build backend image
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ env.LATEST_TAG }} ./NecrosisApi

    - name: Build frontend image
      run: |
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.LATEST_TAG }} ./necrosisapp

    # Set lowercase repo owner for Docker image tags
    - name: Set lowercase owner
      run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      if: success()
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push backend image
      if: success()
      run: |
        docker tag ${{ env.BACKEND_IMAGE }}:${{ env.LATEST_TAG }} ghcr.io/${{ env.REPO_OWNER_LC }}/necrosis-backend:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ env.REPO_OWNER_LC }}/necrosis-backend:${{ env.LATEST_TAG }}

    - name: Tag and push frontend image
      if: success()
      run: |
        docker tag ${{ env.FRONTEND_IMAGE }}:${{ env.LATEST_TAG }} ghcr.io/${{ env.REPO_OWNER_LC }}/necrosis-frontend:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ env.REPO_OWNER_LC }}/necrosis-frontend:${{ env.LATEST_TAG }}
